language: node_js
node_js:
 - "8.11.2"
install:
 - npm install -g jake
 - npm install
 - jake --jakefile jake.js makeLocalDatabases
services:
 - postgresql
env:
 - PGTEST="postgres://localhost:5432/testmailbox"
 - PGDEVELOPMENT="postgres://localhost:5432/mailbox"
